### ISSUE TITLE
Is `--float` broken?

### ISSUE THREAD

**Issue by pmatos** [csmith-project/csmith#172]
If I generate a program with `--float` using cmith 2.4.0, and then compile with gcc 14.1.1, I see that we are passing `float *` to `transparent_crc_bytes` as first argumnet which should have type `char *`. GCC definitely does not like that.

Attaching csmith generated file.
[test1.c.gz](https://github.com/user-attachments/files/16029913/test1.c.gz)

```
test1.c:1617:28: error: passing argument 1 of ‘transparent_crc_bytes’ from incompatible pointer type [-Wincompatible-pointer-types]
 1617 |     transparent_crc_bytes (&g_2320, sizeof(g_2320), "g_2320", print_hash_value);
      |                            ^~~~~~~
      |                            |
      |                            const float *
```

**Comment by pmatos** [comment]
ping. @eeide are you still working on this?

**Comment by pmatos** [comment]
Same as #129 
Interestingly clang happily compiles it as seen in #135

**Comment by eeide** [comment]
Hi, @pmatos! I personally haven't made any substantive code changes to Csmith in a long time.

The most recent changes to Csmith have been from people offering patches through pull requests. A patch for the issue you pointed out would be most welcome!

**Comment by pmatos** [comment]
> Hi, @pmatos! I personally haven't made any substantive code changes to Csmith in a long time.
> 
> The most recent changes to Csmith have been from people offering patches through pull requests. A patch for the issue you pointed out would be most welcome!

I see. Thanks for the quick reply.
